### ISSUE TITLE
Busy cursor stays visible when the user is asked if they want to save their service

### ISSUE THREAD

**Issue by gbfsound** [ghjpk/planningcenter#1]
If a service is already present, and you import a service, it will ask you if you want to save the existing service.  The busy cursor is turned on when the "do you want to save" popup comes up and the user does not realize that they can click because they are waiting for the "mouse pointer" cursor to reappear before clicking.  Need to start the "busy cursor" after the "do you want to save" query is complete.

**Comment by ghjpk** [comment]
Resolved on 7/30
