### ISSUE TITLE
Issue with song formatting

### ISSUE THREAD

**Issue by ghjpk** [ghjpk/planningcenter#10]
On the song, "To God Be The Glory", the formatting is very messed up.  I believe the issue is that the plugin is auto-creating verses for each line break, and then when an actual "Verse 2" type heading shows up, it appends to the previously, auto-created Verse 2 instead of continuing the auto-verse-numbering.

Workaround is to remove the extra line breaks in the middle of the verses and chorus.  Then, the slides are at least in the right order, though, you may not have the number of lines on each slide that you want.

Verse 1
To God be the glory
Great things He has done
So loved He the world
That He gave us His Son

Who yielded His life
An atonement for sin
And opened the life gate
That we may go in

Chorus
Praise the Lord
Praise the Lord
Let the earth
Hear His voice

Praise the Lord
Praise the Lord
Let the people rejoice

O come to the Father
Through Jesus the Son
And give Him the glory
Great things He has done

Verse 2
O perfect redemption
The purchase of blood
To every believer
The promise of God

The vilest offender
Who truly believes
That moment from Jesus
A pardon receives

Chorus
Praise the Lord
Praise the Lord
Let the earth
Hear His voice

Praise the Lord
Praise the Lord
Let the people rejoice

O come to the Father
Through Jesus the Son
And give Him the glory
Great things He has done

Verse 3
Great things
He has taught us
Great things
He has done
And great our rejoicing
Through Jesus the Son

But purer and higher
And greater will be
Our wonder our gladness
When Jesus we see.

Chorus
Praise the Lord
Praise the Lord
Let the earth
Hear His voice

Praise the Lord
Praise the Lord
Let the people rejoice

O come to the Father
Through Jesus the Son
And give Him the glory
Great things He has done
{<b>END</b>}

**Comment by ghjpk** [comment]
Other workaround is to delete the "Verse 1", "Verse 2", etc titles.  That would let the auto-formatting do its thing.

**Comment by brownium** [comment]
Ya, I’ll delete the verse headings, no problem.

**Comment by ghjpk** [comment]
Resolved.  When the lyrics specify any verse number, do not auto-increment verse numbers in between slide breaks.
