### ISSUE TITLE
Feature Request: Details of non-song items

### ISSUE THREAD

**Issue by JonathanMeyer2600** [ghjpk/planningcenter#7]
Hi @ghjpk first of all: thanks for this great extension to openlp!

In our planning we use non-song items with details to add bible verses, creeds or confession. It would be awesome to add these details as slides to non-song items. thus we can display them on screen for every to follow.

Looking forward to hearing what you think about this.

Greetings Jonathan

**Comment by ghjpk** [comment]
Hi, Jonathan,
I wanted to do this from the beginning, but non-song, slide content was not initially available in the v2API. 

I understand it might be available now, but PCO says that they are planning to remove the slide editing capability from their web site in 2019 along with a major redesign. 

I imagine that getting the data into slides from the v2API would be pretty easy but if or when PCO discontinues this feature, it won’t work anymore. 

In our Church, we just make everything songs now and it goes into OpenLP fine. 

I’ll take a look at the API to see what’s involved sometime this week.

**Comment by ghjpk** [comment]
Oh. One more thing!  Thank you for being my first, confirmed user that isn’t at my church!  I’m thrilled it works for you!

**Comment by ghjpk** [comment]
Please download the 0.5 release and give it a try.  It pulls the content of "details" for non-song items and creates slides from them.  Disregard my comment above regarding slide data disappearing from the planning center GUI -- I had misunderstood the initial request because I didn't know that the details feature existed in Planning Center.

**Comment by ghjpk** [comment]
Hi, @JonathanMeyer2600 ,
Were you able to try out the new feature?
Thanks,
John

**Comment by JonathanMeyer2600** [comment]
Hi John,
thanks for the implementation!
It's working and exactly what I've been looking for. Was too busy the last weeks to give it a try and since we are still a church plant we don't have regular services yet. But I'm looking forward to using it in the near future :-D
