### ISSUE TITLE
Feature Request: Ignore everything past this tag

### ISSUE THREAD

**Issue by brownium** [ghjpk/planningcenter#9]
I often have alternate verses in Planning Center that I might use some times and leave out other times.  Presently, I have to delete the text and save it somewhere else.  It would be super helpful if I could put a tag that was interpreted as "ignore everything past this point"

Since I personally put {<b>END</b>} at the end of every song in Planning Center, that would be the perfect tag for me.  Though I'd be happy with {END}

**Comment by brownium** [comment]
Heh - expected that my the bold tags around END would be trapped, but, well, you know what I put in my song tags, so I don't need to explain.

**Comment by ghjpk** [comment]
Feature added.  If you have a stand alone tag, {END} or {<*>END<*>}, it will stop importing lyrics at that point.  There must be no white space after the closing curly brace.
